COPY operadoras_de_plano_de_saude_ativas (
REGISTRO_OPERADORA, CNPJ, RAZAO_SOCIAL, NOME_FANTASIA, MODALIDADE,
    LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, DDD, TELEFONE,
    FAX, ENDERECO_ELETRONICO, REPRESENTANTE, CARGO_REPRESENTANTE, REGIAO_DE_COMERCIALIZACAO, DATA_REGISTRO_ANS

)
FROM 'Relatorio_cadop.csv' --CAMINHO DO ARQUIVO
DELIMITER ';' CSV HEADER ENCODING 'UTF8';