COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '1T2023.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '2T2023.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '3T2023.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '4T2023.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '1T2024.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '2T2024.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '3T2024.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';

COPY demonstracoes_contabeis (
	"DATA",REGISTRO_OPERADORA,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICAL,VL_SALDO_FINAL
)
FROM '4T2024.csv'
DELIMITER ';' CSV HEADER ENCODING 'UTF8';